#include "led.h" 
#include "delay.h" 

void GpioInit(void)
{    	 
	RCC->AHB1ENR|=1<<3;//使能PORTD时钟 
	RCC->AHB1ENR|=1<<1;//使能PORTB时钟 
	RCC->AHB1ENR|=1<<2;//使能PORTC时钟 
	GPIO_Set(GPIOD,PIN12,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_PU); //PC11 超声波输出
	GPIO_Set(GPIOD,PIN2,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_PU); //PD2设置
	GPIO_Set(GPIOD,PIN6,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_PU); //PD6设置
	GPIO_Set(GPIOB,PIN3,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_PU); //PB3设置
	GPIO_Set(GPIOD,PIN4,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_PU); //PD4设置 //底层灯光
	GPIO_Set(GPIOB,PIN4,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_PU); //PB4设置  //玻璃被检测控制
	GPIO_Set(GPIOB,PIN4,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_PU);
	GPIO_Set(GPIOD,PIN3,GPIO_MODE_IN,0,0,GPIO_PUPD_NONE); //PD3设置
	GPIO_Set(GPIOD,PIN7,GPIO_MODE_IN,0,0,GPIO_PUPD_NONE); //PD7设置
	
	GPIO_Set(GPIOA,PIN0,GPIO_MODE_AF,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_PD);// PA0设置 超声波Echo用于输入捕获
	GPIO_Set(GPIOA,PIN1,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_PD); //PA1设置 超声波trigger
	GPIO_AF_Set(GPIOA,0,1);	//PA0,AF1
	
	On_Off=0;
	Light_On=0;
	Light_On_Glass_Water = 0;
	Glass_Light_On = 0;
	TransmitSig = 0;
	TriggerOn = 0;
	
}

void UltrasonicTrigger() //触发超声波
{
		TriggerOn=1;
		delay_us(20);                             //输入一个10us的高电平
		TriggerOn=0;
}
