#include "led.h" 
#include "delay.h" 

void GpioInit(void)
{    	 
	RCC->AHB1ENR|=1<<3;//使能PORTD时钟 
	RCC->AHB1ENR|=1<<1;//使能PORTB时钟 
	GPIO_Set(GPIOD,PIN2,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_PU); //PD2设置
	GPIO_Set(GPIOD,PIN5,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_PU); //PD5设置
	GPIO_Set(GPIOD,PIN6,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_PU); //PD8设置
	GPIO_Set(GPIOB,PIN3,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_PU); //PB3设置
	GPIO_Set(GPIOD,PIN3,GPIO_MODE_IN,0,0,GPIO_PUPD_NONE); //PD3设置
	GPIO_Set(GPIOD,PIN7,GPIO_MODE_IN,0,0,GPIO_PUPD_NONE); //PD7设置
	
	On_Off=0;
	Light_On=0; //灯光关闭
	Glass_Light_On = 0;//灯光关闭
	Light_On_Glass_Water = 0;
}
